services:
  auth-db:
    image: mongo
	container_name: auth-db
	restart: always
	command: ["--replSet", "rs0"]
	ports:
	 - "27017:27017"
	volumes:
	 - gaaf_auth_db:/data/db
	networks:
	 - gaaf_auth_mongo

volumes:
  gaaf_auth_db: 	 

	 
networks:
  gaaf_auth_mongo:
	bridge: bridge
	 
	 